### ISSUE TITLE
Discord got terminated.

### ISSUE THREAD

**Issue by turbopug2735** [atellies/EpicGamesStoreIPA#1]
The celestial discord server got terminated. Can a new one be published?

**Comment by cchase9875** [comment]
I’m hoping so. I really liked it in there

**Comment by atellies** [comment]
Creating a new one and appealing the termination

**Comment by cchase9875** [comment]
> Creating a new one and appealing the termination

Do we know what caused the termination?

**Comment by SSM0770** [comment]
Someone immediately hijacked the vanity link that’s on the repository info, you may want to remove that.

**Comment by atellies** [comment]
> Someone immediately hijacked the vanity link that’s on the repository info, you may want to remove that.



> I’m hoping so. I really liked it in there



> The celestial discord server got terminated. Can a new one be published?

https://discord.gg/SzR5ykEe8D

was dmca because que sent a raw file instead of a link

**Comment by Polar258** [comment]
Can you add me on discord, I need help. This is my user, hate.polar

**Comment by Tashy116** [comment]
link is down

**Comment by atellies** [comment]
> link is down

https://discord.gg/SzR5ykEe8D
