### ISSUE TITLE
Fortnite MacOS

### ISSUE THREAD

**Issue by itsfelipeh** [atellies/EpicGamesStoreIPA#10]
Could you modify it to be used on macOS with M1, M2, M3? I'm signing it with a developer certificate with the proper entitlements, but the message keeps popping up: "Error popup for incorrect entitlements." Cheers.

<img width="862" alt="Screenshot_2024-08-27_at_4 49 40_PM" src="https://github.com/user-attachments/assets/99afa16c-63b7-4847-b48a-fcca6532dc4f">

**Comment by JeffreyBlanz** [comment]
Click Mac Catalyst as well as the same entitlements needed for iOS. 

It works.

**Comment by st-ivan** [comment]
> Could you modify it to be used on macOS with M1, M2, M3? I'm signing it with a developer certificate with the proper entitlements, but the message keeps popping up: "Error popup for incorrect entitlements." Cheers.
> <img alt="Screenshot_2024-08-27_at_4 49 40_PM" width="862" src="https://private-user-images.githubusercontent.com/11917772/361972802-99afa16c-63b7-4847-b48a-fcca6532dc4f.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjUwMTc2NTUsIm5iZiI6MTcyNTAxNzM1NSwicGF0aCI6Ii8xMTkxNzc3Mi8zNjE5NzI4MDItOTlhZmExNmMtNjNiNy00ODQ3LWI0OGEtZmNjYTY1MzJkYzRmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA4MzAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwODMwVDExMjkxNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYwMzFiYWEwMmEzMTI3MmJiOWI1MmU3OGE0ZTJiNzY5MjYzNzk1MGE5NmQ2MTkzNDdjZGM3YTc4YjEyMTFhNDUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.D30ehNERrAESyLvetZh2CWA4G0TxukR-Z2WEWWTnYJY">

how do you modify these entitelments? i have sideloadly and my own free certificate.. will it work on mac m2?

**Comment by itsfelipeh** [comment]
> Haga clic en Mac Catalyst y obtenga los mismos derechos necesarios para iOS.
> 
> Funciona.

how do you modify these entitelments? i have sideloadly and my own certificate.. will it work on mac m3?

**Comment by JeffreyBlanz** [comment]
enable "Extended Virtual Addressing", "Increased Memory Limit", and 
"Mac Catalyst"
