### ISSUE TITLE
Epic Games Store IPA itself?

### ISSUE THREAD

**Issue by andreimotin** [atellies/EpicGamesStoreIPA#2]
Hey,
Found this repo to get Fortnite/Fall Guys IPA directly for side loading. Is there a way you can share the IPA of Epic Games Store itself?
Thanks,
Andrei Motin

**Comment by xanderpolitis** [comment]
theoretically i think it would be able to update the fall guys app &/ fortnite if you could get it...

**Comment by andreimotin** [comment]
Yeah, that would’ve been neat, but my question was if You can share the IPAs not only for the 2 games, but also the IPA for the store. I don’t have it myself, I’m wondering if you could share it here.

**Comment by atellies** [comment]
> Yeah, that would’ve been neat, but my question was if You can share the IPAs not only for the 2 games, but also the IPA for the store. I don’t have it myself, I’m wondering if you could share it here.

the app is useless, you can install with it no point in having it if you’re sideloading

**Comment by andreimotin** [comment]
Why? I’ll be able to update games, install the new ones that will release there and so on. I mean not the app like an app, but as a store from which I’ll be able to install other appsOn Aug 22, 2024, at 12:57 PM, atellies ***@***.***> wrote:﻿

Yeah, that would’ve been neat, but my question was if You can share the IPAs not only for the 2 games, but also the IPA for the store. I don’t have it myself, I’m wondering if you could share it here.

the app is useless, you can install with it no point in having it if you’re sideloading
